### ISSUE TITLE
fix your wiki link's format

### ISSUE THREAD

**Issue by Arman-Espiar** [argotic-syndication-framework/Argotic#35]
please fix your wiki link in GitHub, those are ugly format.  for example  [Generating an RSS feed](https://raw.githubusercontent.com/wiki/argotic-syndication-framework/Argotic/generating-an-rss-feed.md)

**Comment by HowardvanRooijen** [comment]
PR's gratefully accepted!

**Comment by HowardvanRooijen** [comment]
Fixed
