### ISSUE TITLE
Targeting NETSTANDARD2.1 prevents use with .NET4.8

### ISSUE THREAD

**Issue by matthewDDennis** [argotic-syndication-framework/Argotic#7]
Is there a reason to target netstandard2.1 rather than netstandard2.0.  
2.1 can't be used by the .NET Framework.

**Comment by HowardvanRooijen** [comment]
Would the previous release work for you? https://www.nuget.org/packages/Argotic.Common/2008.0.2 

We upgraded to .Net Standard 2.1 because that's the version we use internally.

**Comment by matthewDDennis** [comment]
The Microsoft recommendation is that libraries target the lowest version of net standard that they need so that the library can be consumed by the most apps. Or other libraries. If a library targets 2.1 it can consume net standard 2.0. 
 .net472 and .net48 can consume netstandard2.0 libraries.

**Comment by HowardvanRooijen** [comment]
Fixed by e9df431568d037f08507fb75a5f44ad7240f1445
